version: '3.7'

# from https://github.com/zeebe-io/zeebe-simple-monitor/

services: 
  zeebe:
    container_name: zeebe
    build: ./zeebe
    environment:
        - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "5701:5701"
    volumes:
      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml

  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - io.zeebe.monitor.connectionString=zeebe:26500
      - io.zeebe.monitor.hazelcast.connection=zeebe:5701
    ports:
      - "8080:8080"
    depends_on:
        - zeebe
